fix: continue when Eslint Annotation fails and add check for output of eslint-check step

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -70,6 +70,7 @@ jobs:
         run: npm ci
 
       - name: Run eslint-check and generate report
+        id: eslint-check
         run: |
           npm run eslint-check -- --output-file eslint_report.json --format json
         continue-on-error: true
@@ -79,6 +80,14 @@ jobs:
         with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           report-json: eslint_report.json
+        continue-on-error: true
+      
+      - name: Check eslint-check outcome
+        if: steps.eslint-check.outcome != 'success'
+        run: |
+          echo "::error::eslint-check failed. View output of _Run eslint-check and generate report_ step"
+          exit 1
+
 
   test:
     name: test
